version: "3.6"
services:

  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./shared-workspace:/opt/workspace
    networks:
      basico:
        ipv4_address: 10.11.0.7
  
  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace
    networks:
      basico:
        ipv4_address: 10.11.0.2
  
  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      basico:
        ipv4_address: 10.11.0.3

  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      basico:
        ipv4_address: 10.11.0.4


  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=webadm
      - POSTGRES_PASSWORD=A123456
    ports:
      - "5432:5432"
    deploy:
        resources:
            limits:
              memory: 512M
    volumes:
      - ./dumps:/var/lib/postgresdumps
      - ./volumes/postgres11:/var/lib/postgresql/data
    networks:
      basico:
        ipv4_address: 10.11.0.5


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
       - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      basico:
        ipv4_address: 10.11.0.6



networks:
  basico:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/24
        
